### ISSUE TITLE
In the pinout table for the ItsyBitsy M4, the D12 Arduino name is wrong

### ISSUE THREAD

**Issue by MichaelMeissner** [adafruit/Adafruit-ItsyBitsy-M4-PCB#2]
In the pinout page for the ItsyBitsy M4 ([ItsyBitsy M4 pinout](https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4/pinouts)) the 5th pin on the right side from the top has the wrong Arduino name.

The pinout lists the pin to have an Arduino name of '10'.  However, '10' is used two rows down.  It should have the Arduino name of '12' to match the CircuitPython name of D12, and the text on the PCB.  I had code reading from pin 10, and it didn't work until I changed it to 12 on the ItsyBitsy M4 Express.

**Comment by ladyada** [comment]
hmm - this looks ok to us? can you point out he error and we'll fix :)
![image](https://user-images.githubusercontent.com/1214161/182450418-52c46c0a-a0dc-4726-bb41-7eb190d0ff3b.png)

**Comment by evaherrada** [comment]
Ah yeah I see it. Will add to my list

**Comment by nomadbyte** [comment]
Yep, still a problem. D12 should be 12 (not 10)

In case anyone needs it, attached is a .png image with the corrected pinout.

![Adafruit ItsyBitsy M4 Pinout](https://github.com/adafruit/Adafruit-ItsyBitsy-M4-Express-PCB/assets/1738281/624345e9-f689-4ddd-bb56-03c8d92c06f2)

**Comment by evaherrada** [comment]
Will get this done very soon
